name: Find diff
description: |
  Finds and compares two commits and outputs lists with the differences.

branding:
  icon: git-pull-request
  color: gray-dark

inputs:
  paths:
    description: Search path(s) to limit the search to. Space separated list. Defaults to 'everything'.
    default: "**"

outputs:
  pattern:
    description: A egrep-style pattern consisting of all matches
    value: ${{ steps.diff.outputs.pattern }}
  list:
    description: A list of all matches
    value: ${{ steps.diff.outputs.list }}
  matches:
    description: A boolean value to indicate if there was at least one match.
    value: ${{ steps.diff.outputs.matches }}

runs:
  using: composite
  steps:
    - name: Find diff
      id: diff
      shell: bash
      env:
        PATHS: ${{ inputs.paths }}
      run: |
        # script:

        [ -d ".git" ] || { printf '::error title=.git not found.::Did you forget to check out?\n'; exit 1; }
        echo '::group::Verbose git output'
        git config advice.detachedHead false
        case "$GITHUB_EVENT_NAME" in
          pull_request|pull_request_target)
            git fetch origin "$GITHUB_BASE_REF" "$GITHUB_HEAD_REF"
            git checkout "$GITHUB_BASE_REF"
            git checkout -
            CHANGES=$(git diff --stat=10000 "$GITHUB_BASE_REF")
            ;;
          push)
            git fetch origin "$GITHUB_REF"
            CHANGES=$(git show --stat=10000 --pretty=oneline "$GITHUB_REF")
            ;;
          workflow_dispatch)
            DEFAULT=$(jq -r '.repository.default_branch' "$GITHUB_EVENT_PATH")
            if [ "$DEFAULT" = "$GITHUB_REF_NAME" ]; then
              git fetch origin "$GITHUB_REF"
              CHANGES=$(git show --stat=10000 --pretty=oneline "$GITHUB_REF")
            else # assuming all workflow dispatches not run on default branch should be diffed against the default branch
              git fetch origin "$DEFAULT" "$GITHUB_REF"
              git checkout "$DEFAULT"
              git checkout -
              CHANGES=$(git diff --stat=10000 "$DEFAULT")
            fi
            ;;
          *)
            echo '::endgroup::'
            printf '::error title=Invalid event::Event %s is not supported.\n' "$GITHUB_EVENT_NAME"
            exit 1
            ;;
        esac
        echo '::endgroup::'

        printgroup() {
          printf '::group::%s\n' "$1"
          printf '%s\n' "$2"
          echo '::endgroup::'
        }

        printgroup Changes "$CHANGES"

        SUBSTITUTIONS='
        s|/|\\/|g;
        s|\.|\\.|g;
        s|([^*])\*([^*])|\1[^/]+\2|g;
        s|^\*([^*])|[^/]+\1|g;
        s|([^*])\*$|\1[^/]+|g;
        s|^\*$|[^/]+|g;
        s|\*\*|.*|g;
        s/ /|^/g;
        '

        SEARCH=^$(echo "$PATHS" | sed -E "$SUBSTITUTIONS")

        printgroup "Applied pattern" "$SEARCH"

        LIST=$(printf '%s' "$CHANGES" | grep '|' | sed -E 's/^ *//g; s/(.*)\s\|.*/\1/g; s/\s*$//g' | (grep -oE "$SEARCH" || true) | sort -u)
        printgroup "Change list" "${LIST:-No changes matched.}"

        PATTERN=$(printf '%s' "$LIST" | xargs -r printf '^%s|' | sed 's/|$//g')
        printgroup "Change pattern" "${PATTERN:-No changes matched.}"

        if [ -z "$LIST" ]; then
          {
            printf 'list=\n'
            printf 'pattern=\n'
            printf 'matches=false\n'
          } >> "$GITHUB_OUTPUT"
          exit 0
        fi

        EOF=$(head -c 20 /dev/random | md5sum | head -c 32)
        {
          printf "list<<%s\n" "$EOF"
          printf "%s\n" "$LIST"
          printf "%s\n" "$EOF"
          printf "pattern=%s\n" "$PATTERN"
          printf 'matches=true\n' >> "$GITHUB_OUTPUT"
        } >> "$GITHUB_OUTPUT"
