name: Run

on:
  workflow_dispatch:
    inputs:
      paths:
        description: The paths to use
        required: true
        default: "**"
  pull_request: {}
  push:
    branches:
      - main

jobs:
  run:
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - name: Env
        shell: bash
        run: env

      - name: Event
        shell: bash
        run: cat "$GITHUB_EVENT_PATH"

      - uses: actions/checkout@v3

      - name: Action
        id: run
        uses: ./
        with:
          paths: ${{ inputs.paths || '**' }}

      - name: Outputs
        shell: bash
        run: |
          # Outputs:
          printf 'Pattern:\n${{ steps.run.outputs.pattern }}\n'
          printf '\nList:\n---\n${{ steps.run.outputs.list }}\n'
          printf '\nMatches:\n---\n${{ steps.run.outputs.matches }}\n'
