name: Tests

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run each test
        shell: bash
        run: |
          # Run tests:
          printf '#!/bin/bash\n' > run.sh
          yq '.runs[].0.run' < action.yaml >> run.sh
          chmod +x run.sh
          find .github/workflows/tests -type f -name '*.[sS][hH]' -exec sh -c '
            for file do
              printf "Testing %s ...\n" "$(basename $file ".sh")"
              if ! sh .github/workflows/test-wrapper.sh "$file" run.sh; then
                kill -s PIPE "$PPID"
                exit 1
              fi
            done' sh {} +

          [ $? -eq 0 ] || {
              echo "Tests failed!"
              exit 1
          }

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare script for ShellCheck
        shell: bash
        run: |
          printf '#!/bin/bash\n' > run.sh
          yq '.runs[].0.run' < action.yaml >> run.sh
          chmod +x run.sh

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - unit-tests
      - shellcheck

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0
