name: Tests

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run each test
        shell: bash
        run: |
          # Run tests:
          printf '#!/bin/bash\n' > run.sh
          yq '.runs[].0.run' < action.yaml >> run.sh
          chmod +x run.sh
          RUN=$(readlink -fem run.sh)
          find .github/workflows/tests -name "*.sh" -type f -print0 | xargs -0 -n1 sh -c 'printf "Testing %s ...\n" "$(basename $1 ".sh")"; sh .github/workflows/test-wrapper.sh "$2" "$1"' "$RUN" --

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare script for ShellCheck
        shell: bash
        run: |
          printf '#!/bin/bash\n' > run.sh
          yq '.runs[].0.run' < action.yaml >> run.sh
          chmod +x run.sh

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - unit-tests
      - shellcheck

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0
