name: Tests

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare action for testing
        shell: bash
        run: |
          printf '#!/bin/bash\n' > run.sh
          yq '.runs[].0.run' < action.yaml >> run.sh
          chmod +x run.sh

      - name: Run each test
        shell: bash
        run: |
          mv run.sh .github/workflows
          cd .github/workflows

          find tests -name "*.sh" -type f -exec sh -c 'printf "Test %s:\n" "$(basename $1 ".sh")"; sh test-wrapper.sh "$1" ../run.sh' -- {} \;

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare script for ShellCheck
        shell: bash
        run: |
          printf '#!/bin/bash\n' > run.sh
          yq '.runs[].0.run' < action.yaml >> run.sh
          chmod +x run.sh

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - unit-tests
      - shellcheck

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0
